# Generated by Django 3.2.1 on 2021-05-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_historial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='endTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='historial',
            name='startTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='endTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='startTime',
            field=models.TimeField(),
        ),
    ]
