# Generated by Django 3.2.1 on 2021-05-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20210509_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='task',
        ),
    ]
